### PR TITLE
Configure Github action to run compatibility tests of Erlang based driver

### LINKED ISSUE #431: [Erlang base driver compatibility] configure GH action to run on pull request
Part of #430

### PR DESCRIPTION
**Pull request by silathdiir**
Closes #431 

#### Description

Configures Github action to run compatibility tests on Erlang driver `epgsql`.
And add some `simple` test cases (will add `extended` and other tests for latter PRs).

Developer could also run Erlang Common Test on local by a script `local/erlang_compatibility.sh`.

Erlang could be installed via [asdf](https://github.com/asdf-vm/asdf).

1. Installs `asdf`: https://asdf-vm.com/#/core-manage-asdf?id=install

2. Runs the below shell commands to install Erlang.

```
asdf plugin-add erlang
asdf install erlang 23.1

asdf global erlang 23.1
asdf local erlang 23.1
asdf shell erlang 23.1
```

Rebar is an Erlang tool for managing the project (include `ct` - Common Test).
It could be installed via https://github.com/erlang/rebar3#getting-started.

Finally run the script `local/erlang_compatibility.sh` for local test.

#### Is it a feature that change user experience?

No.

#### Client output

```
$ ./local/erlang_compatibility.sh

===> Verifying dependencies...
===> Analyzing applications...
===> Compiling extra_tests/erlang_compatibility
===> Running Common Test suites...

Common Test starting (cwd is /Users/asongala/sql/database)

TEST INFO: 1 test(s), 4 case(s) in 1 suite(s)

Testing tests.erlang_compatibility: Starting test, 4 test cases
%%% simple_basic_queries_SUITE: ....
Testing tests.erlang_compatibility: TEST COMPLETE, 4 ok, 0 failed of 4 test cases

Updating /**/database/erlang_compatibility_logs/index.html ... done
Updating /**/database/erlang_compatibility_logs/all_runs.html ... done
```

### CODE REVIEW

**Comment by alex-dukhno** [comment]
Hi @silathdiir, I hope you are not going to write same tests as in groovy but in Erlang/Elixir 😄 
My idea was to somehow make https://github.com/epgsql/epgsql#test-setup to run on CI.

**Comment by silathdiir** [comment]
Hi @alex-dukhno , do you mean we should try to start our `database` service, download `epgsql` and run the `epgsql` tests only on our `database` service in CI? 😂

**Comment by alex-dukhno** [comment]
yes
but all configuration setup is better done under #432
for #431 to have 1 Erlang file is ok, to make sure that CI is running and epgsql can communicate with database.

`database` should start as a docker container. Here could be problems see #437. I haven't check but:
```yaml
on:
  - pull_request_taget
```
could help with security tokens and fork based contributions

**Comment by alex-dukhno** [comment]
If `pull_request_taget` won't help ... I think for now it will be ok to configure job on schedule, I don't think that all `epgsql` tests will pass immediately 😄

**Comment by silathdiir** [comment]
Hi @alex-dukhno , I thought about publishing a new docker image with tag of last Commit ID of the PR (has not found how to retrieve the last Commit ID), then testing on a new docker container. But it seems that it is complicated and may run a long time for this test.

So I tried with another method  as below (temporary fixing in the file `pull_request.yml` now):

```
  common-tests:
...
      - name: run-tests
        run: cargo build && cargo run & cargo build && sleep 1 && rebar3 ct --dir tests/erlang_compatibility/ --logdir erlang_compatibility_logs/ -v
```

It seems that it works, since the command `cargo build && cargo run &` starts the `database` server in background, and `cargo build && sleep 1 && rebar3` runs the Erlang tests.
The second `cargo build && sleep 1` is tricky, since it could run (blocked by `cargo`) until the first `cargo build` finishes, and `sleep 1` could wait for `cargo run` which always finishes in `0.2s`.

I will try to add a new script for the long command (as `ci/clippy.sh`) if you agree. WDYT?

**Comment by alex-dukhno** [comment]
I am fine with that, will see if it works with epgsql tests, I think it should. 

Also would be super cool if compatibility tests will run on pull request not on the merge into master.

**Comment by silathdiir** [comment]
Will close this PR after testing to add Java Compatibility tests to Github action on pull requests.

**Comment by silathdiir** [comment]
PR #447 is used for Java Compatibility tests, so close this test.

**Pull request closed without merging**
