### PR TITLE
Implements SQL statement Prepare, Execute and Deallocate

### LINKED ISSUE #278: Implement SQL statements Prepare, Execute and Deallocate
The Postgres doc: https://www.postgresql.org/docs/current/sql-prepare.html#SQL-PREPARE-EXAMPLES .

The crate `sqlparser-rs` needs to be upgraded to include the PR: https://github.com/ballista-compute/sqlparser-rs/pull/243 .

These three statements should be considered as one part of Prepared Statement (another one is Extended Query), and should be implemented and integrated with the current implementation of Prepared Statement (in session).

It is used for Prepared Statement. Please reference more information in PR #274 .

### PR DESCRIPTION
**Pull request by silathdiir**
Closes #278 

#### Description

Implements SQL statement Prepare, Execute and Deallocate as part of Prepared Statement feature.

#### Is it a feature that change user experience?

No

#### Client output

```
psql (12.1, server 0.0.0)
Type "help" for help.

xxx=> create schema schema_name;
CREATE SCHEMA
xxx=> create table schema_name.table_name (col1 smallint, col2 smallint, col3 smallint);
CREATE TABLE
xxx=> prepare fooplan (smallint, smallint) as insert into schema_name.table_name values ($1, $2, $3);
PREPARE
xxx=> execute fooplan(1, 2, 3);
INSERT 0 1
xxx=> deallocate fooplan;
DEALLOCATE
xxx=> select * from schema_name.table_name;
 col1 | col2 | col3
------+------+------
    1 |    2 |    3
(1 row)
```

### CODE REVIEW

**Comment by silathdiir** [comment]
Hi @alex-dukhno , please help review this PR if you have time. Thanks.

**Review by alex-dukhno — CHANGES_REQUESTED** [review]
Hi @silathdiir, thanks for the PR.
I am in the process of simplification of the `protocol` module. #386 is the first one on this road. I want that `protocol` has code to handle state machine of hand shake and message passing between client and server. That would allow to remove most of dependencies from it. These are under my radar different `async-*`, `blocking`, `byteorder` and `rand`. 

Also I was thinking that some logic should be moved out of `protocol`. I see that you added `bigdecimal` and `sqlparser` for `PostgreSqlType`. I think this is a good candidate to be moved out.

Can you please in this PR `src/protocol/src/pgsql_types.rs` move into `pg_model` cargo module, so that it will depend on `protocol` and then `node` will depend on `pg_model`?

Thanks

**Comment by silathdiir** [comment]
OK, I see. I will try to move `src/protocol/src/pgsql_types.rs` associating code to `pg_model`.

**Review by alex-dukhno — APPROVED** [review]
I'll change to raw `u32` instead of `PostgreSqlType` in `FrontendMessage::Parse` and `i32` instead of `PostgreSqlFormat` in `FrontendMessage::Bind`, once I finish with `protocol` refactoring.
I suppose it will require moving `Command` and `Receiver`, `Sender` somewhere.

Thanks for the PR.

**Pull request merged**
